"""
memnos.storage.qdrant_backend — Qdrant vector backend implementation.

Each memnos Memory is stored as a Qdrant point:
  point_id  : the memory UUID string
  vector    : named vectors — "dense" (OpenAI embeddings) + optionally "sparse" (BM25)
  payload   : {namespace, memory_type, superseded}

Hybrid search uses Qdrant's built-in Reciprocal Rank Fusion (RRF) via
Prefetch + FusionQuery when fastembed is installed.  If fastembed is not
available the backend falls back transparently to dense-only search.

Sparse vectors are generated by fastembed's BM25 model (Qdrant/bm25),
which runs entirely on CPU — no GPU required.

Install optional sparse support:
    pip install fastembed

Namespace filtering uses exact match only (Qdrant does not support prefix
matching natively). Parent-namespace expansion is handled upstream in
MemnosClient.search() via the existing while-loop retry.

Requires: qdrant-client >= 1.9  (``pip install 'qdrant-client>=1.9'``)

Migration note
--------------
Existing collections created before this version used a flat VectorParams
config (no named vectors).  When an upsert detects this mismatch it logs a
one-time warning and falls back to dense-only upsert so the service keeps
running.  To enable hybrid search on an existing collection you must either:
  a) Drop and recreate the collection (data loss — re-index from ArcadeDB), or
  b) Create a new collection name via MEMNOS_QDRANT_COLLECTION and migrate.
"""

from __future__ import annotations

import asyncio
import logging
from typing import Any

from memnos.storage.vector_backend import VectorBackend

logger = logging.getLogger(__name__)

_SUPERSEDED_FIELD = "superseded"
_NAMESPACE_FIELD  = "namespace"

# Sentinel used to mark "tried to load fastembed but it is not installed".
_UNAVAILABLE = "unavailable"


class QdrantVectorBackend(VectorBackend):
    """
    VectorBackend implementation backed by a Qdrant collection.

    The collection is created automatically on first use if it does not exist.
    Hybrid (dense + BM25 sparse) search is used when fastembed is installed;
    otherwise pure dense search is used.
    """

    def __init__(
        self,
        url: str = "http://localhost:6333",
        api_key: str | None = None,
        collection: str = "memnos_memories",
        vector_dim: int = 1536,
    ) -> None:
        self._url = url
        self._api_key = api_key
        self._collection = collection
        self._vector_dim = vector_dim
        self._client: Any = None  # qdrant_client.AsyncQdrantClient

        # Sparse encoder state.  None = not yet attempted.
        # _UNAVAILABLE = fastembed not installed.
        # A SparseTextEmbedding instance = ready to use.
        self._sparse_encoder: Any = None
        # True once we have confirmed (or created) a collection with named
        # vectors config.  False means the collection uses the legacy flat
        # config and we must degrade to dense-only for writes.
        self._has_named_vectors: bool = False
        # Log the migration warning at most once per process lifetime.
        self._migration_warned: bool = False

    # Public, read-only attributes for the admin endpoint and ops tooling.
    @property
    def url(self) -> str:
        return self._url

    @property
    def collection(self) -> str:
        return self._collection

    @property
    def vector_dim(self) -> int:
        return self._vector_dim

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    async def _ensure_client(self) -> Any:
        if self._client is None:
            try:
                from qdrant_client import AsyncQdrantClient  # type: ignore
            except ImportError as exc:
                raise ImportError(
                    "qdrant-client is required for the Qdrant vector backend. "
                    "Install it with: pip install 'qdrant-client>=1.9'"
                ) from exc
            kwargs: dict[str, Any] = {"url": self._url}
            if self._api_key:
                kwargs["api_key"] = self._api_key
            self._client = AsyncQdrantClient(**kwargs)
            await self._ensure_collection()
        return self._client

    async def _ensure_collection(self) -> None:
        from qdrant_client.models import (  # type: ignore
            Distance,
            SparseVectorParams,
            VectorParams,
        )

        client = self._client
        existing = await client.get_collections()
        names = [c.name for c in (existing.collections or [])]

        if self._collection not in names:
            # Create with named-vectors config (dense + sparse).
            await client.create_collection(
                collection_name=self._collection,
                vectors_config={
                    "dense": VectorParams(size=self._vector_dim, distance=Distance.COSINE),
                },
                sparse_vectors_config={
                    "sparse": SparseVectorParams(),
                },
            )
            self._has_named_vectors = True
            logger.info(
                "Qdrant: created collection '%s' (dim=%d, cosine, sparse=BM25)",
                self._collection, self._vector_dim,
            )
        else:
            # Inspect the existing collection to decide whether it has named vectors.
            info = await client.get_collection(self._collection)
            vectors_cfg = info.config.params.vectors
            # Named-vectors collections have a dict-like vectors config;
            # legacy flat collections have a single VectorParams object.
            self._has_named_vectors = isinstance(vectors_cfg, dict)
            if self._has_named_vectors:
                logger.debug(
                    "Qdrant: collection '%s' has named vectors (hybrid search enabled)",
                    self._collection,
                )
            else:
                logger.warning(
                    "Qdrant: collection '%s' uses legacy flat-vector config — "
                    "hybrid search is DISABLED for this collection. "
                    "To enable hybrid search, drop and recreate the collection "
                    "or set a new collection name via MEMNOS_QDRANT_COLLECTION.",
                    self._collection,
                )

    async def close(self) -> None:
        if self._client is not None:
            try:
                await self._client.close()
            except Exception as exc:
                logger.debug("Qdrant close error (ignored): %s", exc)
            finally:
                self._client = None

    # ------------------------------------------------------------------
    # Sparse encoder helpers
    # ------------------------------------------------------------------

    async def _get_sparse_encoder(self) -> Any:
        """Return a loaded SparseTextEmbedding instance, or None if unavailable.

        On the first call this attempts to import fastembed and load the BM25
        model (Qdrant/bm25) in a thread pool so the event loop is not blocked.
        Subsequent calls return the cached result immediately.
        """
        if self._sparse_encoder is _UNAVAILABLE:
            return None
        if self._sparse_encoder is not None:
            return self._sparse_encoder

        # First call — try to load fastembed.
        try:
            def _load() -> Any:
                from fastembed import SparseTextEmbedding  # type: ignore
                return SparseTextEmbedding(model_name="Qdrant/bm25")

            self._sparse_encoder = await asyncio.to_thread(_load)
            logger.info(
                "BM25 sparse encoder loaded (fastembed Qdrant/bm25) — hybrid search active"
            )
        except ImportError:
            self._sparse_encoder = _UNAVAILABLE
            logger.info(
                "fastembed not installed — using dense-only search. "
                "Install with: pip install fastembed"
            )
        except Exception as exc:
            self._sparse_encoder = _UNAVAILABLE
            logger.warning(
                "Failed to load fastembed BM25 encoder (%s) — "
                "falling back to dense-only search.", exc,
            )
        return None if self._sparse_encoder is _UNAVAILABLE else self._sparse_encoder

    async def _get_sparse_vector(self, text: str) -> Any:
        """Return a SparseVector for *text*, or None if fastembed is unavailable."""
        enc = await self._get_sparse_encoder()
        if enc is None:
            return None

        def _encode() -> Any:
            results = list(enc.embed([text]))
            if not results:
                return None
            r = results[0]
            from qdrant_client.models import SparseVector  # type: ignore
            return SparseVector(
                indices=r.indices.tolist(),
                values=r.values.tolist(),
            )

        return await asyncio.to_thread(_encode)

    # ------------------------------------------------------------------
    # VectorBackend interface
    # ------------------------------------------------------------------

    async def upsert(
        self,
        memory_id: str,
        embedding: list[float],
        namespace: str,
        memory_type: str = "fact",
        text: str | None = None,
    ) -> None:
        from qdrant_client.models import PointStruct  # type: ignore

        client = await self._ensure_client()

        payload = {
            _NAMESPACE_FIELD: namespace,
            "memory_type": memory_type,
            _SUPERSEDED_FIELD: False,
        }

        if self._has_named_vectors:
            # Build named-vector payload, adding sparse if fastembed is available
            # and text was provided.
            vector_payload: dict[str, Any] = {"dense": embedding}
            if text:
                sparse_vec = await self._get_sparse_vector(text)
                if sparse_vec is not None:
                    vector_payload["sparse"] = sparse_vec

            point = PointStruct(id=memory_id, vector=vector_payload, payload=payload)
            try:
                await client.upsert(collection_name=self._collection, points=[point])
            except Exception as exc:
                # Guard against edge cases where the collection config diverges
                # from what _ensure_collection detected (e.g. external recreation).
                err_str = str(exc).lower()
                if "vector" in err_str or "config" in err_str or "named" in err_str:
                    if not self._migration_warned:
                        logger.warning(
                            "Qdrant named-vector upsert failed — falling back to dense-only. "
                            "Error: %s", exc,
                        )
                        self._migration_warned = True
                    # Retry with legacy flat-vector format.
                    fallback_point = PointStruct(
                        id=memory_id, vector=embedding, payload=payload
                    )
                    await client.upsert(
                        collection_name=self._collection, points=[fallback_point]
                    )
                else:
                    raise
        else:
            # Legacy flat-vector collection — dense only.
            point = PointStruct(id=memory_id, vector=embedding, payload=payload)
            await client.upsert(collection_name=self._collection, points=[point])

        logger.debug("Qdrant upsert: %s in %s", memory_id, namespace)

    async def search(
        self,
        embedding: list[float],
        namespace: str,
        top_k: int = 10,
        include_superseded: bool = False,
        text: str | None = None,
    ) -> list[tuple[str, float]]:
        from qdrant_client.models import Filter, FieldCondition, MatchValue  # type: ignore

        client = await self._ensure_client()

        # When namespace is "all" / "" / "*" the caller wants a global search;
        # ACL filtering is applied upstream — skip the namespace clause here.
        _cross_ns = namespace.lower().strip() in ("", "all", "*")

        conditions = []
        if not _cross_ns:
            conditions.append(
                FieldCondition(key=_NAMESPACE_FIELD, match=MatchValue(value=namespace))
            )
        if not include_superseded:
            conditions.append(
                FieldCondition(key=_SUPERSEDED_FIELD, match=MatchValue(value=False))
            )

        query_filter = Filter(must=conditions) if conditions else None

        # Attempt hybrid RRF search when the collection supports named vectors
        # and a query text is available for sparse encoding.
        if self._has_named_vectors and text:
            sparse_vec = await self._get_sparse_vector(text)
            if sparse_vec is not None:
                return await self._hybrid_rrf_search(
                    client=client,
                    embedding=embedding,
                    sparse_vec=sparse_vec,
                    query_filter=query_filter,
                    top_k=top_k,
                )

        # Dense-only search (named-vectors collection uses "dense" key;
        # legacy flat-vector collection omits the `using` argument).
        if self._has_named_vectors:
            result = await client.query_points(
                collection_name=self._collection,
                query=embedding,
                using="dense",
                query_filter=query_filter,
                limit=top_k,
                with_payload=False,
                with_vectors=False,
            )
        else:
            # qdrant-client >= 1.10 replaced search() with query_points()
            result = await client.query_points(
                collection_name=self._collection,
                query=embedding,
                query_filter=query_filter,
                limit=top_k,
                with_payload=False,
                with_vectors=False,
            )

        return [(str(h.id), float(h.score)) for h in result.points]

    async def _hybrid_rrf_search(
        self,
        client: Any,
        embedding: list[float],
        sparse_vec: Any,
        query_filter: Any,
        top_k: int,
    ) -> list[tuple[str, float]]:
        """Run Qdrant's built-in RRF fusion across dense and sparse prefetch arms."""
        from qdrant_client.models import Fusion, FusionQuery, Prefetch  # type: ignore

        # Each prefetch arm fetches more candidates than top_k to give RRF
        # sufficient overlap before re-ranking.
        prefetch_limit = top_k * 2

        result = await client.query_points(
            collection_name=self._collection,
            prefetch=[
                Prefetch(
                    query=embedding,
                    using="dense",
                    limit=prefetch_limit,
                    filter=query_filter,
                ),
                Prefetch(
                    query=sparse_vec,
                    using="sparse",
                    limit=prefetch_limit,
                    filter=query_filter,
                ),
            ],
            query=FusionQuery(fusion=Fusion.RRF),
            limit=top_k,
            with_payload=False,
            with_vectors=False,
        )
        return [(str(h.id), float(h.score)) for h in result.points]

    async def delete(self, memory_id: str) -> None:
        from qdrant_client.models import PointIdsList  # type: ignore

        client = await self._ensure_client()
        await client.delete(
            collection_name=self._collection,
            points_selector=PointIdsList(points=[memory_id]),
        )
        logger.debug("Qdrant delete: %s", memory_id)

    async def mark_superseded(self, memory_id: str) -> None:
        from qdrant_client.models import SetPayload  # type: ignore

        client = await self._ensure_client()
        await client.set_payload(
            collection_name=self._collection,
            payload={_SUPERSEDED_FIELD: True},
            points=[memory_id],
        )
        logger.debug("Qdrant mark_superseded: %s", memory_id)
