"""
Harness adapter generation — the `tommy generate` implementation.

Projects tommy.yaml's resolved policy into whichever coding-harness config
format(s) a project already has evidence of using:

    - Claude Code  -> CLAUDE.md                          (inject a block)
    - Cursor       -> .cursor/rules/tommy.mdc             (whole file, Tommy-owned)
    - Windsurf     -> .windsurfrules                      (inject a block)
    - Copilot      -> .github/copilot-instructions.md     (inject a block)

Every write goes through explicit idempotent markers
(`<!-- TOMMY:BEGIN -->` / `<!-- TOMMY:END -->`) so re-running `tommy generate`
only ever replaces the marked region — anything a human wrote above, below,
or around it in the same file is untouched. All four target formats are
markdown/plain-text, so one HTML-comment marker syntax covers all of them;
there's no adapter target in this issue's scope (a JSON or TOML config file,
say) that would need a different comment syntax.

Presence detection (which files `tommy generate` will touch without an
explicit --create-missing): a file counts as "present" if the file itself
already exists, OR — for Cursor/Copilot, which don't put a single file at
the project root — if the tool's own directory (`.cursor/`, `.github/`)
already exists, since that's real evidence the project already uses that
harness/platform. tommy.yaml existing is not by itself evidence of harness
choice (harness choice is explicitly local/machine-specific per issue #113),
so `tommy generate` never invents adapter files out of thin air unless told
to with --create-missing.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Callable

from .effective_config import EffectiveConfig

BEGIN_MARKER = "<!-- TOMMY:BEGIN -->"
END_MARKER = "<!-- TOMMY:END -->"

_CURSOR_FRONTMATTER = """---
description: Tommy project policy (generated — see tommy.yaml)
alwaysApply: true
---
"""


def render_policy_block(effective: EffectiveConfig) -> str:
    """Render the human-readable policy body that goes between markers.
    Same content for every adapter target — only the surrounding file
    format (frontmatter, comment syntax) differs."""
    v = effective.value
    name = v("project_name") or "(unnamed project)"
    key = v("project_key") or "(no key)"
    namespace = v("namespace") or "(none configured)"
    design_docs = v("design_docs")
    design_docs_line = ", ".join(design_docs) if design_docs else "(none configured)"

    lines = [
        "# Tommy Project Policy",
        "",
        "Generated by `tommy generate` from `tommy.yaml`. Do not hand-edit this",
        "block — edit tommy.yaml and re-run `tommy generate` instead; this whole",
        "region will be replaced, not merged.",
        "",
        f"- Project: {name} ({key})",
        f"- memnos namespace: {namespace}",
        f"- Design docs: {design_docs_line}",
        f"- Corpus gate: {'on' if v('corpus_gate') else 'off'} "
        "(dispatch must call corpus_check() before proceeding when on)",
        f"- Auto-ingest design docs into corpus: {'on' if v('auto_ingest') else 'off'}",
        f"- Merge gate: {'on' if v('merge_gate') else 'off'} "
        "(wave-based dispatch required when on)",
        f"- Wave limit: {v('wave_limit')} (max subagent dispatches per turn)",
        "- Agents:"
        f" harness={v('harness')},"
        f" default_model={v('default_model')},"
        f" smart_routing={'on' if v('smart_routing') else 'off'}",
    ]
    return "\n".join(lines)


def upsert_marked_block(existing: str, body: str) -> str:
    """Replace the region between BEGIN_MARKER/END_MARKER with `body`,
    preserving everything else in `existing` byte-for-byte. If no valid
    marker pair is found, the block is appended to the end instead."""
    block = f"{BEGIN_MARKER}\n{body}\n{END_MARKER}"

    begin_idx = existing.find(BEGIN_MARKER)
    end_idx = existing.find(END_MARKER)
    if begin_idx != -1 and end_idx != -1 and end_idx > begin_idx:
        end_idx += len(END_MARKER)
        return existing[:begin_idx] + block + existing[end_idx:]

    # No existing markers — append (creating separation from any existing content).
    prefix = existing
    if prefix and not prefix.endswith("\n"):
        prefix += "\n"
    if prefix and not prefix.endswith("\n\n"):
        prefix += "\n"
    return prefix + block + "\n"


@dataclass
class AdapterTarget:
    name: str
    rel_path: str
    is_present: Callable[[Path], bool]
    render_new_file: Callable[[str], str]  # given the policy body, full fresh-file content


def _cursor_present(root: Path) -> bool:
    return (root / ".cursor").exists()


def _github_present(root: Path) -> bool:
    return (root / ".github").exists() or (root / ".github" / "copilot-instructions.md").exists()


def _simple_present(rel_path: str) -> Callable[[Path], bool]:
    return lambda root: (root / rel_path).exists()


ADAPTER_TARGETS: list[AdapterTarget] = [
    AdapterTarget(
        name="claude",
        rel_path="CLAUDE.md",
        is_present=_simple_present("CLAUDE.md"),
        render_new_file=lambda body: upsert_marked_block("", body),
    ),
    AdapterTarget(
        name="cursor",
        rel_path=".cursor/rules/tommy.mdc",
        is_present=_cursor_present,
        render_new_file=lambda body: _CURSOR_FRONTMATTER + upsert_marked_block("", body),
    ),
    AdapterTarget(
        name="windsurf",
        rel_path=".windsurfrules",
        is_present=_simple_present(".windsurfrules"),
        render_new_file=lambda body: upsert_marked_block("", body),
    ),
    AdapterTarget(
        name="copilot",
        rel_path=".github/copilot-instructions.md",
        is_present=_github_present,
        render_new_file=lambda body: upsert_marked_block("", body),
    ),
]


@dataclass
class AdapterWriteResult:
    target: AdapterTarget
    path: Path
    action: str  # "created" | "updated" | "unchanged" | "skipped" | "dry-run"


def generate_adapters(
    effective: EffectiveConfig,
    project_root: Path,
    *,
    create_missing: bool = False,
    dry_run: bool = False,
) -> list[AdapterWriteResult]:
    """Write/update every adapter target that is present (or all of them, if
    create_missing=True). Returns one AdapterWriteResult per target that was
    actually touched (present ones, plus all of them if create_missing)."""
    body = render_policy_block(effective)
    results: list[AdapterWriteResult] = []

    for target in ADAPTER_TARGETS:
        present = target.is_present(project_root)
        if not present and not create_missing:
            results.append(AdapterWriteResult(target, project_root / target.rel_path, "skipped"))
            continue

        path = project_root / target.rel_path
        if path.exists():
            before = path.read_text()
            after = upsert_marked_block(before, body)
            action = "unchanged" if after == before else "updated"
        else:
            after = target.render_new_file(body)
            action = "created"

        if dry_run:
            results.append(AdapterWriteResult(target, path, f"dry-run:{action}"))
            continue

        if action != "unchanged":
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(after)
        results.append(AdapterWriteResult(target, path, action))

    return results


def render_stdout_fallback(effective: EffectiveConfig) -> str:
    body = render_policy_block(effective)
    header = (
        "No recognized harness config file (CLAUDE.md, .cursor/, .windsurfrules, "
        ".github/) was found under this project root, so nothing was written.\n"
        "Create one of those (or pass --create-missing) and re-run `tommy generate`.\n"
        "Generated policy block:\n"
    )
    return header + "\n" + f"{BEGIN_MARKER}\n{body}\n{END_MARKER}\n"
